Repository NCAR/ccpp-physics, pull requests merged in 2022-06, with the labels that each got.

#940 Emergency fix: exponentiation instead of multiplication caused bad 2m temperatures
  physics/module_sf_mynn.F90
Labels: bug

#932 Update README.md links for release/public-v6
  README.md
Labels: documentation, CCPP v6

#943 Modification made to reflect the V6 release plan change
  physics/docs/pdftxt/GFS_v17_p8_suite.txt
  physics/docs/pdftxt/RAP_suite.txt
  physics/docs/pdftxt/RE6/FV3_GFS_v17_p8_input.nml
  physics/docs/pdftxt/RE6/FV3_RAP_input.nml
  physics/docs/pdftxt/RE6/SCM_GFS_v17_p8_input.nml
  physics/docs/pdftxt/RE6/SCM_RAP_input.nml
  physics/docs/pdftxt/RE6/suite_SCM_GFS_v17_p8.xml
  physics/docs/pdftxt/RE6/suite_SCM_RAP.xml
  physics/docs/pdftxt/all_shemes_list.txt
  physics/docs/pdftxt/mainpage.txt
  physics/radlw_main.F90
  physics/radsw_main.F90
Labels: CCPP v6
